import { useDispatch } from "react-redux";
import { setApi } from "../Store/Reducer";

var api=[{"house_id":"1","house_name":"Nest Craft","description":"Nest Builders","flat":"2","house_price":"9.53","marketing_company":"Nest Builder","house_img":"https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg","owner_name":"Josh singh","house_address":"Owner 2 BHK Flat for Sale in Perfect Residency Kolathur","house_area":"Sithalapakkam","super_area":"980","under_construction":"8/7/2022","transaction":"Resale","furnishing":"Unfurnishing","car_parking":"","bathroom":"3","floor":"1 out of 3","lift":"1","status":"Ready to Move","rera_id":"TN/01/Building/0131/2017","flooring":"Vetrified","water_availability":"24 Hours Available",'resident':'Flat'},
        {"house_id":"2","house_name":"Nest Mascot II","description":"Nest Builders","flat":"3","house_price":"47.8","marketing_company":"Nest Builder","house_img":"https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg","owner_name":"Josh singh","house_address":"Owner 3 BHK Flat for Sale in Real Value Neel Old  Magarastra","house_area":"Maharastra","super_area":"1055","under_construction":"5/22/2022","transaction":"new","furnishing":"Unfurnishing","car_parking":"","bathroom":"2","floor":"8 out of 20","lift":"","status":"Ready to Move","rera_id":"TN/10/Building/9151/2019","flooring":"Unvetrified","water_availability":"15 Hours Available",'resident':'House'},
        {"house_id":"3","house_name":"Bhaggayam Athulya","description":"Petrus pyram air cel inc","flat":"4","house_price":"11","marketing_company":"Topicstorm","house_img":"https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg","owner_name":"smackil","house_address":"Owner 4 BHK Flat for Sale in Perfect Residency Maharastra","house_area":"SholingaNallur","super_area":"1451","under_construction":"12/2/2023","transaction":"Resale","furnishing":"Furnishing","car_parking":"1 Covered","bathroom":"3","floor":"1","lift":"2","status":"Ready to Move","rera_id":"TN/05/Building/9151/2013","flooring":"vetrified","water_availability":"24 Hours Available",'resident':'Plot'},
        {"house_id":"4","house_name":"Marutham Royal","description":"Non-op hearing proc NEC","flat":"5","house_price":"15.5","marketing_company":"Twitterbeat","house_img":"https://cdn.staticmb.com/property/microsite/mb-banners/00738634/featureproject-img.jpg","owner_name":"sonnelly","house_address":"Owner 2 BHK Flat for Sale in Perfect Residend adaiyar ","house_area":"Stevena","super_area":"1386","under_construction":"6/21/2021","transaction":"Resale","furnishing":"Unfurnishing","car_parking":"","bathroom":"2","floor":"5 out of 12","lift":"1","status":"","rera_id":"TN/05/Building/9151/2022","flooring":"","water_availability":"12 Hour Available ",'resident':'House'},
        {"house_id":"5","house_name":"Nest Craft","description":"Nest Builders","flat":"1","house_price":"7.53","marketing_company":"Nest Builder","house_img":"https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg","owner_name":"Josh singh","house_address":"Owner 2 BHK Flat for Sale in Perfect Residency Kolathur","house_area":"Sithalapakkam","super_area":"980","under_construction":"8/7/2022","transaction":"Resale","furnishing":"Unfurnishing","car_parking":"1 Covered","bathroom":"3","floor":"1 out of 3","lift":"1","status":"Ready to Move","rera_id":"TN/01/Building/0131/2017","flooring":"Vetrified","water_availability":"24 Hours Available",'resident':'Plot'},
        {"house_id":"6","house_name":"Nest Mascot II","description":"Nest Builders","flat":"6","house_price":"47.8","marketing_company":"Nest Builder","house_img":"https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg","owner_name":"Josh singh","house_address":"Owner 3 BHK Flat for Sale in Real Value Neel Old  Magarastra","house_area":"Maharastra","super_area":"1055","under_construction":"5/22/2022","transaction":"new","furnishing":"Unfurnishing","car_parking":"","bathroom":"2","floor":"8 out of 20","lift":"","status":"Ready to Move","rera_id":"TN/10/Building/9151/2019","flooring":"Unvetrified","water_availability":"15 Hours Available",'resident':'Flat'},
        {"house_id":"7","house_name":"Bhaggayam Athulya","description":"Petrus pyram air cel inc","flat":"4","house_price":"10","marketing_company":"Topicstorm","house_img":"https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg","owner_name":"smackil","house_address":"Owner 4 BHK Flat for Sale in Perfect Residency Maharastra","house_area":"SholingaNallur","super_area":"1451","under_construction":"12/2/2023","transaction":"Resale","furnishing":"Furnishing","car_parking":"1 Covered","bathroom":"3","floor":"1","lift":"2","status":"Ready to Move","rera_id":"TN/05/Building/9151/2013","flooring":"vetrified","water_availability":"24 Hours Available",'resident':'Plot'},
        {"house_id":"8","house_name":"Marutham Royal","description":"Non-op hearing proc NEC","flat":"2","house_price":"15.5","marketing_company":"Twitterbeat","house_img":"https://cdn.staticmb.com/property/microsite/mb-banners/00738634/featureproject-img.jpg","owner_name":"sonnelly","house_address":"Owner 2 BHK Flat for Sale in Perfect Residend adaiyar ","house_area":"Stevena","super_area":"1386","under_construction":"6/21/2021","transaction":"Resale","furnishing":"Unfurnishing","car_parking":"","bathroom":"2","floor":"5 out of 12","lift":"1","status":"","rera_id":"TN/05/Building/9151/2022","flooring":"","water_availability":"12 Hour Available", 'resident':'Flat'},
        {"house_id":"9","house_name":"Nest Craft","description":"Nest Builders","flat":"2","house_price":"6.53","marketing_company":"Nest Builder","house_img":"https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg","owner_name":"Josh singh","house_address":"Owner 2 BHK Flat for Sale in Perfect Residency Kolathur","house_area":"Sithalapakkam","super_area":"980","under_construction":"8/7/2022","transaction":"Resale","furnishing":"Unfurnishing","car_parking":"1 Covered","bathroom":"3","floor":"1 out of 3","lift":"1","status":"Ready to Move","rera_id":"TN/01/Building/0131/2017","flooring":"Vetrified","water_availability":"24 Hours Available",'resident':'House'},
        {"house_id":"10","house_name":"Nest Craft","description":"Nest Builders","flat":"6","house_price":"6.53","marketing_company":"Nest Builder","house_img":"https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg","owner_name":"Josh singh","house_address":"Owner 2 BHK Flat for Sale in Perfect Residency Kolathur","house_area":"Sithalapakkam","super_area":"980","under_construction":"8/7/2022","transaction":"Resale","furnishing":"Unfurnishing","car_parking":"1 Covered","bathroom":"3","floor":"1 out of 3","lift":"1","status":"Ready to Move","rera_id":"TN/01/Building/0131/2017","flooring":"Vetrified","water_availability":"24 Hours Available",'resident':'Flat'},
]
export const Api=()=>{
    const dispatch=useDispatch()
    dispatch(setApi(api))
 }